version: '3.8'

services:
  gameprice-web:
    build:
      context: ..
      dockerfile: GamePrice/Dockerfile
    ports:
      - "8080:80"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ApiSettings__GamePriceApiUrl=http://gameprice-api:5200
    depends_on:
      - gameprice-api
    networks:
      - gameprice-network

  gameprice-api:
    build:
      context: ..
      dockerfile: GamePrice.Api/Dockerfile
    ports:
      - "5200:5200"
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_URLS=http://+:5200
      - ApiSettings__ScraperApiUrl=http://gameprice-scraper:8000
    depends_on:
      - gameprice-scraper
    networks:
      - gameprice-network

  gameprice-scraper:
    build:
      context: ../GamePrice.Scraper
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    networks:
      - gameprice-network

networks:
  gameprice-network:
    driver: bridge
